Repository teamCampro/campro_BE, pull requests merged in 2024-02, with the labels that each got.

#32 🚑 Hotfix : cd.yml 수정 #31
  .github/workflows/cd.yml
Labels: :safety_vest: 데브옵스, :fire: 핫픽스

#38 🔧 Config: spring security setting #20
  build.gradle
  src/main/java/com/campro/common/config/WebSecurityConfig.java
Labels: ⚙️ 환경설정, :alarm_clock: 중요도-중

#42 ✨️Feat: member form signup #24
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/campro/CamproBeApplication.java
  src/main/java/com/campro/common/config/WebSecurityConfig.java
  src/main/java/com/campro/common/controller/ExceptionControllerAdvice.java
  src/main/java/com/campro/common/exception/ApiException.java
  src/main/java/com/campro/common/exception/ErrorCode.java
  src/main/java/com/campro/common/infrastructure/entity/BaseTimeEntity.java
  src/main/java/com/campro/encrypt/application/service/EncryptService.java
  src/main/java/com/campro/encrypt/application/service/EncryptServiceImpl.java
  src/main/java/com/campro/encrypt/config/EncryptConfig.java
  src/main/java/com/campro/encrypt/config/EncryptProperties.java
  src/main/java/com/campro/member/application/MemberDetailService.java
  src/main/java/com/campro/member/application/MemberService.java
  src/main/java/com/campro/member/application/MemberServiceImpl.java
  src/main/java/com/campro/member/application/request/MemberSignupRequest.java
  src/main/java/com/campro/member/domain/EncryptMember.java
  src/main/java/com/campro/member/domain/Member.java
  src/main/java/com/campro/member/domain/Role.java
  src/main/java/com/campro/member/infrastructure/JpaMemberRepository.java
  src/main/java/com/campro/member/infrastructure/MemberRepository.java
  src/main/java/com/campro/member/infrastructure/MemberRepositoryImpl.java
  src/main/java/com/campro/member/infrastructure/entity/MemberEntity.java
  src/main/java/com/campro/member/presentation/controller/MemberController.java
  src/main/java/com/campro/member/presentation/controller/response/MemberSignupResponse.java
  src/test/java/com/campro/member/controller/middle/MemberControllerTest.java
  src/test/java/com/campro/member/service/small/MemberServiceTest.java
  src/test/java/com/campro/mock/EncryptFakeService.java
  src/test/java/com/campro/mock/MemberFakeRepository.java
  src/test/resources/application.properties
Labels: 💡 기능, :sos: 중요도-상, 🤖 테스트

#46 ✨ Feat: member login #43
  build.gradle
  src/main/java/com/campro/auth/application/AuthTokenService.java
  src/main/java/com/campro/auth/application/JwtService.java
  src/main/java/com/campro/auth/config/JwtProperties.java
  src/main/java/com/campro/auth/domain/Token.java
  src/main/java/com/campro/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/campro/auth/infrastructure/JpaTokenRepository.java
  src/main/java/com/campro/auth/infrastructure/TokenRepository.java
  src/main/java/com/campro/auth/infrastructure/TokenRepositoryImpl.java
  src/main/java/com/campro/auth/infrastructure/entity/TokenEntity.java
  src/main/java/com/campro/common/config/WebSecurityConfig.java
  src/main/java/com/campro/common/exception/ErrorCode.java
  src/main/java/com/campro/encrypt/application/service/EncryptService.java
  src/main/java/com/campro/encrypt/application/service/EncryptServiceImpl.java
  src/main/java/com/campro/member/application/MemberService.java
  src/main/java/com/campro/member/application/MemberServiceImpl.java
  src/main/java/com/campro/member/application/request/MemberLoginRequest.java
  src/main/java/com/campro/member/presentation/controller/MemberController.java
  src/main/java/com/campro/member/presentation/controller/response/MemberLoginResponse.java
  src/test/java/com/campro/member/service/small/MemberServiceTest.java
  src/test/java/com/campro/mock/EncryptFakeService.java
  src/test/java/com/campro/mock/FakeTokenService.java
Labels: 💡 기능, :sos: 중요도-상
